\input texinfo  @c -*-texinfo-*-

@c %**start of header
@setfilename mksc68.info
@include version.texi
@include package.texi
@settitle @command{sc68}: @value{DESCRIPTION}
@finalout
@c %**end of header

@dircategory @value{INFOCAT}
@direntry
* mksc68: (mksc68).           @value{DESCRIPTION}
@end direntry

@synindex cp ky
@setchapternewpage odd

@ifinfo
This is Edition @value{EDITION} of @cite{The @command{mksc68} Manual},
for @command{mksc68} version @value{VERSION}, last updated @value{UPDATED}.
@c !BEGIN INTRO
@c !END INTRO

@c !BEGIN COPYING
@*Copyright @copyright{} 2010-2011 Benjamin Gerard

Permission is granted to make and distribute verbatim copies of
this manual upon condition that the  provided the copyright notice
and this permission notice are preserved on all copies.
@c !END COPYING
@end ifinfo

@titlepage
@title mksc68
@subtitle 
@sp 1
@subtitle Edition @value{EDITION}, for @command{mksc68} version @value{VERSION} @value{UPDATED}
@c !BEGIN AUTHORS
@author Benjamin Gerard
@c !END AUTHORS
@end titlepage
@c @page

@ifinfo
@node Top, mksc68 Program, (dir), (dir)
@top @command{mksc68}: create and modify sc68 files

The @command{mksc68} is used to create or modify sc68 music files.


@ignore
@c !BEGIN NAME
/|\ Atari ST and C= Amiga music player.
@c !END NAME
@end ignore


@menu
* mksc68 Program::             The @command{mksc68} Program
* Options Summary::            Options Summary
@end menu

@center manual for mksc68 version @value{VERSION} edited on @value{UPDATED}

@end ifinfo

@node mksc68 Program, Options Summary, Top, Top
@section The @command{mksc68} Program

@section Description
@c !BEGIN DESCRIPTION
@command{mksc68} is a program to play mksc68 music file.
@c !END DESCRIPTION

@c !BEGIN SYNOPSIS
@section Synopsis
@display
@command{mksc68 [OPTION] [--] <URI>}
@end display
@c !END SYNOPSIS

@node Options Summary,  , mksc68 Program, Top
@c !BEGIN OPTIONS
@section Options Summary

@option{--} breaks option parsing.

@subsection Informationnal Options
@table @samp
@item  @option{-h}
@itemx @option{--help}
Display help message and exit.
@item  @option{-V}
@itemx @option{--version}
Display build date and exit.
@end table

@subsection General Options
@table @samp
@item  @option{-t}
@itemx @option{--track=track[,loop]}
Choose track to play [0=all-tracks] and number of loop [0=infinite]
@item  @option{-o <output-uri>}
@itemx @option{--output=<output-uri>}
Set output. Default is stdout. 
@end table

@subsection sc68 Engine Options
@c TODO $$$ insert a link to generic sc68 options here
@c !END OPTIONS

@ignore
@c !BEGIN SEEALSO
The full documentation for @command{mksc68} is maintained as a Texinfo manual. If the @command{info} and @command{mksc68} programs are properly installed at your site, the command

@command{info mksc68}

should give you access to the complete manual.
@c !END SEEALSO
@end ignore

@page
@contents
@bye
